#if !defined(Bytecode_Csq4_H)
#define Bytecode_Csq4_H
#define LPAR (
#define RPAR )
#define LSQB [
#define RSQB ]
#define COLON :
#define COMMA ,
#define SEMI ;
#define PLUS +
#define MINUS -
#define STAR *
#define SLASH /
#define VBAR |
#define AMPER &
#define AND &&
#define OR ||
#define LESS <
#define GREATER >
#define EQUAL =
#define DOT .
#define PERCENT %
#define LBRACE {
#define RBRACE }
#define EQEQUAL ==
#define NOTEQUAL !=
#define LESSEQUAL <=
#define GREATEREQUAL >=
#define TILDE  ~
#define IN :
#define POW ^
#define PLUSEQUAL +=
#define MINEQUAL -=
#define STAREQUAL *=
#define SLASHEQUAL /=
#define PERCENTEQUAL %=
#define AMPEREQUAL &=
#define INCREMENT ++
#define DECREMENT --
#endif // Bytecode_Csq4_H